name: Build and Push Docker Image to ECR and Redeploy ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::816069165502:role/gh-actions-pedido-service-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR (no cache)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pedido-service
          IMAGE_TAG: latest
        run: |
          echo "🔁 Forçando build sem cache..."
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region us-east-1 || \
          aws ecr create-repository --repository-name $ECR_REPOSITORY --region us-east-1

          docker image rm $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG || true
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster microservices-cluster \
            --service pedido-service \
            --force-new-deployment \
            --region us-east-1
